// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://othnpzfrtsesvwfwjfpr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im90aG5wemZydHNlc3Z3ZndqZnByIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5MjU1MDcsImV4cCI6MjA2NzUwMTUwN30.quhOcQUmerWlmg-dXqIF9TCi3P_XP0DNSDyCo6b-ejc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});